[package]
name = "graphite-sink"
group = "infinyon-labs"
version = "0.1.1"
apiVersion = "0.1.0"
fluvio = "0.10.0"
description = ""
license = "Apache-2.0"
visibility = "public"

[direction]
 dest = true

[deployment]
binary = "graphite-sink"

[graphite.properties.metric-path]
title = "Metric Path"
description = "Metric namespace to populate"
type = "string"

[graphite.properties.addr]
title = "Address"
description = "TCP Address to send metrics"
type = "string"
