version: '3'

services:
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-4
    ports:
      - '12345:80'
      - '2003-2004:2003-2004'
      - '2023-2024:2023-2024'
      - '8125:8125/udp'
      - '8126:8126'
      - '5672:5672'
    volumes:
      - ./.graphite/conf:/opt/graphite/conf
