meta:
  version: 0.1.0
  name: my-graphite-connector-test-connector
  type: graphite-connector-sink
  topic: test-graphite-connector-topic
custom:
  amqp_addr: amqp://localhost:5672
  # https://graphite.readthedocs.io/en/latest/feeding-carbon.html#step-1-plan-a-naming-hierarchy
  metric_path: "weather.temperature.ca.sandiego"
